"""Added phone Column

Revision ID: 13dcafd7c7f1
Revises: dbe071e38418
Create Date: 2025-05-01 08:01:09.493358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13dcafd7c7f1'
down_revision: Union[str, None] = 'dbe071e38418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('phone', sa.Numeric(precision=11), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'phone')
    # ### end Alembic commands ###
