"""removed phone Column

Revision ID: 9ca994de2e00
Revises: 13dcafd7c7f1
Create Date: 2025-05-01 08:04:27.137448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9ca994de2e00'
down_revision: Union[str, None] = '13dcafd7c7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('phone', mysql.DECIMAL(precision=11, scale=0), nullable=True))
    # ### end Alembic commands ###
